### ISSUE TITLE
Support 2PC JTA Transaction support for apps running in Liberty

### ISSUE THREAD

**Issue by kelapure** [cloudfoundry/ibm-websphere-liberty-buildpack#325]
Liberty profile supports 2PC transactions and the JCA spec (since 8.5.5.2).  The WebSphere Liberty Profile deliberately sets `-Dcom.ibm.tx.jta.disable2PC=true` because Cloud Foundry containers lack persistent disk support. This custom system property disables support for two phase commit in distributed global transactions; however Liberty allows  writing transaction logs to an external DB instead to the local file system .[see](http://www.ibm.com/support/knowledgecenter/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_store_logs_in_rdb.html). 

_With this approach the app in the container is stateless. The state (transaction log) is managed in a external db._

The JVM property can be set via the manifest.xml file.

```
      env:
        ...
        JVM: openjdk
        JAVA_OPTS: "-Dcom.ibm.tx.jta.disable2PC=false"
        JVM_ARGS: "-Dcom.ibm.tx.jta.disable2PC=false" 
```

With these two modifications JTA 2PC works with apps running in the Liberty Profile. 
1. Is this supported in Bluemix ?
2. Should the `disable2PC` property be removed  in the Liberty buildpack ?

@jgawor
