### ISSUE TITLE
Cannot find Liberty Buildpack Version.

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/ibm-websphere-liberty-buildpack#362]
When I deploy the app, I get the following error.

Deploy Log
```
sangjunui-MacBook-Air:get-started-java sangjunyun$ cf push
Using manifest file /Users/sangjunyun/workspace/cf-sample-app/get-started-java/manifest.yml

Updating app GetStartedJava in org services / space prod as ghama...
OK

Uploading GetStartedJava...
Uploading app files from: /var/folders/dm/yx9gxwcd12x9jqs4bzr3ysnw0000gp/T/unzipped-app106003929
Uploading 45.5K, 28 files
Done uploading               
OK

Starting app GetStartedJava in org services / space prod as ghama...
Downloading liberty_buildpack...
Downloaded liberty_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (837.3K)
Staging...
-----> Liberty Buildpack Version: unknown
```

manifest.yml
```
---
applications:
- name: GetStartedJava
  random-route: true
  path: target/GetStartedJava.war
  memory: 1G
  instances: 1
  buildpack: liberty_buildpack
  env:
    IBM_JVM_LICENSE: L-PMAA-A3Z8P2
    IBM_LIBERTY_LICENSE: L-SWIS-AKWR6K
```

buildpacks
```
sangjunui-MacBook-Air:get-started-java sangjunyun$ cf buildpacks
Getting buildpacks...

buildpack              position   enabled   locked   filename
java_buildpack         1          true      false    java-buildpack-offline-v3.9.zip
staticfile_buildpack   2          true      false    staticfile_buildpack-cached-v1.3.9.zip
ruby_buildpack         3          true      false    ruby_buildpack-cached-v1.6.19.zip
nodejs_buildpack       4          true      false    nodejs_buildpack-cached-v1.5.15.zip
go_buildpack           5          true      false    go_buildpack-cached-v1.7.8.zip
python_buildpack       6          true      false    python_buildpack-cached-v1.5.6.zip
php_buildpack          7          true      false    php_buildpack-cached-v4.3.14.zip
binary_buildpack       8          true      false    binary_buildpack-cached-v1.0.2.zip
liberty_buildpack      9          true      false    ibm-websphere-liberty-buildpack-2.7.0.0.zip
```
CF version : v235
