### ISSUE TITLE
Resolving differences w/ BlueMix

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/ibm-websphere-liberty-buildpack#377]
Hi, 

I'm working with someone who wants to use the Vaadin framework with our Cloud Foundry install at cloud.gov. I'm starting from this sample app, https://github.com/vaadin/framework-bluemix-example, which, of course, deploys seamlessly onto BlueMix.

When I try the same app in BlueMix with the manifest.yml below, it fails with errors about, `Internal Exception: javax.persistence.PersistenceException: CWWJP0013E: The server cannot locate the jdbc/vaadindb data source for the customer-pu persistence unit because it has encountered      the following exception: javax.naming.NameNotFoundException: jdbc/vaadindb`, etc.

Are you all familiar enough with the differences between this buildpack and the IBM one to know how I might resolve this? Or what further information do you need? 

Thanks for providing this buildpack, and thanks in advance for any tips you might have.

```
applications:
- name: vaadinApp
  instances: 1
  memory: 512M
  path: target/vaadin-jpa-application.war
  random-route: true
  services:
    - myexample-db
  buildpack: https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack.git
  env:
    IBM_JVM_LICENSE:  L-(redacted)
    IBM_LIBERTY_LICENSE:  L-(redacated)
```

Update: To clarify: I expected that the application that deployed into BlueMix with their `liberty-for-java` buildpack would also deploy with this buildpack.
